# Generated by Django 6.0.1 on 2026-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0003_remove_review_service_remove_review_service_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='department/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
