# Generated by Django 6.0.1 on 2026-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0004_tasks_image_alter_department_image_alter_users_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proof'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
