# Generated by Django 6.0.1 on 2026-02-19 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_users_id_proof_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.services'),
        ),
    ]
