# Generated by Django 6.0.1 on 2026-02-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.department'),
        ),
        migrations.AlterField(
            model_name='users',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.services'),
        ),
    ]
